#!/bin/bash
# Change wallpaper if needed when invoked

# Add DBUS environment in case run from cron
PID=$(pgrep gnome-session | head -n 1)
export DBUS_SESSION_BUS_ADDRESS=$(grep -z DBUS_SESSION_BUS_ADDRESS /proc/$PID/environ|cut -d= -f2-)

LOGFILE="$HOME/.local/log/wallchanger.log"
function log(){
    echo $1
    echo $(date "+%Y-%m-%d %Hh%M") $1 >> $LOGFILE
}

log "Found PID=$PID DBUS=$DBUS_SESSION_BUS_ADDRESS"

# Read conf
source $HOME/.config/HourlyWallpaper

# Get hour of day
h=$( date +%H )

# Get path to image
f="$PATH_TO_WALLPAPER_FOLDER"
cmd="find $f -name "*$h*""  # find relevant picture

if [ $( $cmd | wc -l ) != 0 ]
then
    p=$( $cmd | head -n 1)  # Get only first result
else
    # No file found
    # Log failure and exit
    log "Error: no file found in $PATH_TO_WALLPAPER_FOLDER for hour $h"
    exit 1
fi

# Change wallpaper
gsettings set org.gnome.desktop.background picture-uri "file://$p"

# Log success
log "Successfully changed to wallpaper $p"
